### ISSUE TITLE
Duration error

### ISSUE THREAD

**Issue by mtirwin** [mapbox/s3signed#2]
@dhcole and I are seeing links expire well before the duration set in the CLI. Links specified for a week (604,800 seconds) are expiring after 2-3 days (maybe sooner; haven't tested). @aaronlidman @rclark anything new in the underlying AWS APIs that'd trip up s3signed?

**Comment by zmully** [comment]
@mtirwin the expire timestamp should be in the URL itself, does that match with what you're expecting?

**Comment by jqtrde** [comment]
I had some difficulties getting signed url's to work a while back: https://github.com/mapbox/pxm/pull/462#issuecomment-174013767

I _think_ that the instance (in my case, a morec2) which was used to generate the key needs to persist so long as you need access to the signed url.

**Comment by zmully** [comment]
ding ding we may have a winner: @jacquestardie 

Some more digging: https://github.com/aws/aws-sdk-ruby/issues/808

Since the URLs are getting signed with our mbx creds, they're only good for at most 12 hours regardless if this is actually the issue.

**Comment by mtirwin** [comment]
Nice detective work. So this isn't a bug, it's an undocumented feature. ;)

Closing here for now and will open a PR to add to the readme.
